### ISSUE TITLE
Investigate staging harvester errors

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#224]
## Why
There are a few errors for the staging harvester that appeared after the data was migrated from Compose to AWS in #221 and #222.

## What
- [x] it is verified if the errors from Staging are related to the data migration.

## Notes
Logs:
```
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain: Getting summary page 8
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain: Traceback (most recent call last):
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain:   File "./extract_summary.py", line 328, in <module>
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain:     sys.exit(main())
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain:   File "./extract_summary.py", line 275, in main
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain:     country = d['country']['label']
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain: KeyError: 'country'
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain: https://staging.resourcedata.org/api/action/organization_show
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain: {u'help': u'https://staging.resourcedata.org/api/3/action/help_show?name=organization_show', u'success': True, u'result': {u'display_name': u'Extractive Industries Transparency Initiative (EITI)', u'users': [{u'email_hash': u'b418e327b1985a550b4737f407e2c000', u'about': u'', u'capacity': u'admin', u'name': u'admin', u'openid': None, u'created': u'2016-12-05T04:37:17.827412', u'sysadmin': True, u'activity_streams_email_notifications': False, u'state': u'active', u'number_of_edits': 107393, u'display_name': u'Staging Admin', u'fullname': u'Staging Admin', u'id': u'b6147337-e8b1-4d5d-87b9-0171897afb24', u'number_created_packages': 10509}, {u'email_hash': u'04af0eef22269d04930b480ba2d069d6', u'about': None, u'capacity': u'editor', u'name': u'anderspeders', u'openid': None, u'created': u'2017-03-21T16:57:08.863324', u'sysadmin': True, u'activity_streams_email_notifications': False, u'state': u'active', u'number_of_edits': 5, u'display_name': u'Anders Pedersen', u'fullname': u'Anders Pedersen', u'id': u'181c9022-a6a2-4e39-a769-49e76366019b', u'number_created_packages': 0}, {u'email_hash': u'dd871158ccc952ea6c676339bfccc8de', u'about': u'', u'capacity': u'editor', u'name': u'tmorrison', u'openid': None, u'created': u'2017-03-30T20:59:17.585797', u'sysadmin': True, u'activity_streams_email_notifications': True, u'state': u'active', u'number_of_edits': 69, u'display_name': u'Thomas Morrison', u'fullname': u'Thomas Morrison', u'id': u'9f779a93-cb01-4692-9e7f-1342efb2652a', u'number_created_packages': 9}], u'created': u'2017-01-26T09:44:04.790954', u'package_count': 51, u'image_display_url': u'https://eiti.org/sites/all/themes/eiti/logo.svg', u'approval_status': u'approved', u'name': u'eiti', u'is_organization': True, u'state': u'active', u'extras': [], u'image_url': u'https://eiti.org/sites/all/themes/eiti/logo.svg', u'groups': [], u'title': u'Extractive Industries Transparency Initiative (EITI)', u'revision_id': u'0d7b3b86-fb78-47c2-9bdb-ca0086c012a4', u'num_followers': 2, u'type': u'organization', u'id': u'16cecb17-b452-4538-82af-783d4c84cbf1', u'tags': [], u'description': u'The Extractive Industries Transparency Initiative (EITI) is a global Standard to promote the open and accountable management of natural resources.\r\n\r\nThe Standard seeks to addresses the key governance issues of the oil, gas and mining sectors.'}}
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain: UPDATING ORG eiti
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain: <Response [409]>
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain: Traceback (most recent call last):
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain:   File "./eiti_import.py", line 234, in <module>
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain:     with open('./datasets.json', 'r') as f:
Apr 12 16:01:49 629acc5cd428 ecs-eiti-harvester-staging-task-4-eiti-harvester-staging-contain: IOError: [Errno 2] No such file or directory: './datasets.json'
Apr 12 16:01:50 ip-10-0-1-56 ecs-agent: 2018-04-12T13:01:50Z [INFO] Recording execution stopped time for a task, essential container in task stopped, task eiti-harvester-staging-task:4 arn:aws:ecs:us-east-1:877912432675:task/76227a0b-8e81-4522-b05b-c4c08df08a51, TaskStatus: (RUNNING->RUNNING) Containers: [eiti-harvester-staging-container (STOPPED->RUNNING),], time: 2018-04-12 13:01:50.167930059 +0000 UTC
```

**Comment by adinuca** [comment]
Same errors are present in production.

One of the datasets does not contain country : https://eiti.org/api/v1.0/summary_data/1116 . 
@EricSoroos , @deirdrelee could you please check what needs to be done about this. It  breaks the harvester both in staging and production at the moment.

**Comment by EricSoroos** [comment]
This is not related to the migration, nor the recent changes to the harvester. EITI has a new entry in their summary data that breaks the harvester. 

The fix here: https://github.com/NRGI/resourcedata.org/tree/issue_224 is running on my machine, It's through the crux issue but not complete. Note that this is a patch against staging, not production. We can either backport this minor fix straight through to production, or we can promote the staging harvester up after running once on staging with this patch.

**Comment by EricSoroos** [comment]
merged to staging.

**Comment by adinuca** [comment]
@EricSoroos , I think you can merge it to master, worst thing is that the harvester would not work, which already happens.

**Comment by EricSoroos** [comment]
Pushed to master

**Comment by adinuca** [comment]
Harvester has been running successfully in the last 2 days.
