### ISSUE TITLE
Investigate error logs that appeared after the migration

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#230]
## Why
Following the migration of data from Compose to AWS  some error logs appeared. We need to understand why and how to fix them.

## What
- [ ] Cause for the error logs is found
- [ ] Issue is raised for fixing them
## Notes
Error messages:
```
Apr 19 11:16:37 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: *** Running /etc/my_init.d/70_initdb...
Apr 19 11:16:37 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: ERROR:  extension "postgis_tiger_geocoder" does not exist
Apr 19 11:16:37 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: Command failed; probably not a problem
Apr 19 11:16:39 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: /usr/lib/ckan/default/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Apr 19 11:16:39 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   SNIMissingWarning
Apr 19 11:16:39 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: /usr/lib/ckan/default/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Apr 19 11:16:39 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   InsecurePlatformWarning
Apr 19 11:16:40 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: /usr/lib/ckan/default/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Apr 19 11:16:40 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   InsecurePlatformWarning
Apr 19 11:16:41 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: 2018-04-19 08:16:41,227 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
Apr 19 11:16:41 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: 2018-04-19 08:16:41,266 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
Apr 19 11:16:41 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: 2018-04-19 08:16:41,293 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
Apr 19 11:16:43 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: Initialising DB: SUCCESS
Apr 19 11:16:44 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: /usr/lib/ckan/default/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Apr 19 11:16:44 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   SNIMissingWarning
Apr 19 11:16:44 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: /usr/lib/ckan/default/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Apr 19 11:16:44 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   InsecurePlatformWarning
Apr 19 11:16:45 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: /usr/lib/ckan/default/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Apr 19 11:16:45 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   InsecurePlatformWarning
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: 2018-04-19 08:16:46,208 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: 2018-04-19 08:16:46,247 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: 2018-04-19 08:16:46,276 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: You are now connected to database "datastore" as user "datastore".
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: REVOKE
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: REVOKE
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: ERROR:  role "ckan" does not exist
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: ERROR:  role "ckan" does not exist
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: GRANT
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: GRANT
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: ERROR:  database "ckan" does not exist
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: GRANT
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: GRANT
Apr 19 11:16:46 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: WARNING:  no privileges were granted for "spatial_ref_sys"
Apr 19 11:16:47 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: WARNING:  no privileges were granted for "geography_columns"
Apr 19 11:16:47 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: WARNING:  no privileges were granted for "geometry_columns"
Apr 19 11:16:47 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: WARNING:  no privileges were granted for "raster_columns"
Apr 19 11:16:47 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: WARNING:  no privileges were granted for "raster_overviews"
Apr 19 11:16:47 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: GRANT
Apr 19 11:16:47 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: ALTER DEFAULT PRIVILEGES
Apr 19 11:16:47 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: CREATE VIEW
Apr 19 11:16:47 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: ALTER VIEW
Apr 19 11:16:47 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: GRANT
Apr 19 11:16:47 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: *** Running /etc/my_init.d/80_initadmin...
Apr 19 11:16:49 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: /usr/lib/ckan/default/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Apr 19 11:16:49 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   SNIMissingWarning
Apr 19 11:16:49 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: /usr/lib/ckan/default/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Apr 19 11:16:49 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   InsecurePlatformWarning
Apr 19 11:16:49 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: /usr/lib/ckan/default/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Apr 19 11:16:49 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   InsecurePlatformWarning
Apr 19 11:16:49 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: 2018-04-19 08:16:49,861 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
Apr 19 11:16:49 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: 2018-04-19 08:16:49,898 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
Apr 19 11:16:49 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: 2018-04-19 08:16:49,925 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
Apr 19 11:16:50 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: Creating user: 'admin'
Apr 19 11:16:50 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: Traceback (most recent call last):
Apr 19 11:16:50 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 132, in user_add
Apr 19 11:16:50 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 457, in wrapped
Apr 19 11:16:50 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:     result = _action(context, data_dict, **kw)
Apr 19 11:16:50 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 961, in user_create
Apr 19 11:16:50 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:     raise ValidationError(errors)
Apr 19 11:16:50 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: ValidationError: {'name': ['That login name is not available.']}
Apr 19 11:16:51 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: /usr/lib/ckan/default/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Apr 19 11:16:51 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   SNIMissingWarning
Apr 19 11:16:51 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: /usr/lib/ckan/default/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Apr 19 11:16:51 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   InsecurePlatformWarning
Apr 19 11:16:51 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: /usr/lib/ckan/default/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Apr 19 11:16:51 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:   InsecurePlatformWarning
Apr 19 11:16:52 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: 2018-04-19 08:16:52,137 DEBUG [ckanext.spatial.plugin] Setting up the spatial model
Apr 19 11:16:52 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: 2018-04-19 08:16:52,175 DEBUG [ckanext.spatial.model.package_extent] Spatial tables defined in memory
Apr 19 11:16:52 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: 2018-04-19 08:16:52,203 DEBUG [ckanext.spatial.model.package_extent] Spatial tables already exist
Apr 19 11:16:52 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: Added admin as sysadmin
Apr 19 11:16:52 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: *** Running /etc/rc.local...
Apr 19 11:16:52 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: *** Booting runit daemon...
Apr 19 11:16:52 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: *** Runit started as PID 330
Apr 19 11:16:52 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: Apr 19 08:16:52 resourcedata syslog-ng[340]: syslog-ng starting up; version='3.5.3'
Apr 19 11:16:52 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501:    ...fail!
Apr 19 11:17:01 resourcedata.org ecs-rd-master-task-73-rd-master-container-c8b3f9bab9beb3fe7e00: Apr 19 08:17:01 resourcedata /USR/SBIN/CRON[536]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Apr 19 11:17:01 resourcedata.org ecs-rd-master-task-74-rd-master-container-ea9fbec8a9f3c1ee9501: Apr 19 08:17:01 resourcedata /USR/SBIN/CRON[474]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Apr 19 11:19:50 resourcedata.org ecs-rd-master-task-73-rd-master-container-c8b3f9bab9beb3fe7e00: *** Shutting down runit daemon (PID 332)...
Apr 19 11:19:50 resourcedata.org ecs-rd-master-task-73-rd-master-container-c8b3f9bab9beb3fe7e00: Apr 19 08:19:50 resourcedata syslog-ng[342]: syslog-ng shutting down; version='3.5.3'
Apr 19 11:19:51 resourcedata.org ecs-rd-master-task-73-rd-master-container-c8b3f9bab9beb3fe7e00: *** Killing all processes...

```

**Comment by adinuca** [comment]
`ERROR:  extension "postgis_tiger_geocoder" does not exist` is not an issue as the script that generates it is droping the extension:

```
#A tiger table interferes with a CKAN table, and we don't need tiger anyway
: ${DATABASE_URL:=}
if [ -z "$DATABASE_URL" ]; then
    DATABASE_URL="postgresql://${DB_ENV_POSTGRES_USER}:${DB_ENV_POSTGRES_PASS}@${DB_PORT_5432_TCP_ADDR}:${DB_PORT_5432_TCP_PORT}/${DB_ENV_POSTGRES_DB}"
fi
psql $DATABASE_URL -c "drop extension postgis_tiger_geocoder" || echo "Command failed; probably not a problem";
```

**Comment by adinuca** [comment]
By taking a closer look at the logs, the errors regarding both the tiger extension,  the user and database not existing and the login name not being available, were present in production in February as well.
