### ISSUE TITLE
No JSON object could be decoded - eiti harvester

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#265]
## Why
New error logs started appearing for eiti harvester on the 11th of April.

## What
- [ ] An investigation is done on why the errors occurred
- [ ] A fix is pushed for eiti-harvester

## Notes
```
Apr 12 10:00:20 ip-10-0-1-43 ecs-agent:  2019-04-12T07:00:20Z [INFO] Managed task [arn:aws:ecs:us-east-1:877912432675:task/2598824f-aba5-4c19-b642-2a3a319ae13c]: redundant container state change. eiti-harvester-master-container to RUNNING, but already RUNNING
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:  Getting summary page 1
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:  Traceback (most recent call last):
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:    File "./eiti.py", line 173, in <module>
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:      main()
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:    File "./eiti.py", line 129, in main
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:      summaries = extract_summary.getSummaryData()
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:    File "/root/eiti_harvester/extract_summary.py", line 112, in getSummaryData
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:      d = session.get(API_ENDPOINT + 'summary_data?page=%s' % page).json()['data']
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:    File "/usr/lib/python2.7/site-packages/requests/models.py", line 866, in json
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:      return complexjson.loads(self.text, **kwargs)
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:    File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:      return _default_decoder.decode(s)
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:    File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:    File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:      raise ValueError("No JSON object could be decoded")
Apr 12 10:00:20 7123dd84bca7 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-bce5a8dbd190af84d801:  ValueError: No JSON object could be decoded
```

**Comment by adinuca** [comment]
Hi @EricSoroos , any idea what caused this error? Thank you!

**Comment by adinuca** [comment]
The error is no longer present in the logs.
