### ISSUE TITLE
Investigate harvester errors

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcedata.org#266]
## Why
EITI harvester has some errors in the logs starting with 23rd of March.

## What
- [x] Errors in logs are investigated
- [ ] A follow-up issue is raised for fixing the error cause.

## Notes
```
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:  Writing ./out/government/democratic-republic-of-congo-government.csv
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:  mauritania 2012
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:  ('Connection aborted.', BadStatusLine("''",))
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:  Traceback (most recent call last):
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:    File "./eiti.py", line 173, in <module>
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:      main()
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:    File "./eiti.py", line 160, in main
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:      extract_summary.gatherCountry(summary)
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:    File "/root/eiti_harvester/extract_summary.py", line 238, in gatherCountry
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:      out_government.append(getLineForRevenue(d, revenue, 'government'))
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:    File "/root/eiti_harvester/extract_summary.py", line 142, in getLineForRevenue
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:      j = session.get(companyurl).json()
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:    File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:      return self.request('GET', url, **kwargs)
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:    File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:      resp = self.send(prep, **send_kwargs)
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:    File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:      r = adapter.send(request, **kwargs)
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:    File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:      raise ConnectionError(err, request=request)
Apr 22 10:02:18 52585410e4a6 ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-fa80d484ffcff2a0cd01:  requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
Apr 22 10:02:19 ip-10-0-1-170 ecs-agent:  2019-04-22T07:02:19Z [INFO] Task [arn:aws:ecs:us-east-1:877912432675:task/38f3cb4e-65d9-44ba-9f3b-827d7663817c]: recording execution stopped time. Essential container [eiti-harvester-master-container] stopped at: 2019-04-22 07:02:19.162338345 +0000 UTC m=+3937880.196219618
```

**Comment by adinuca** [comment]
Hi @EricSoroos ,

We keep seeing errors in the logs for the harvesters. Can you please take a look if there is an issue or if we should ignore this error.

Thank you!

**Comment by EricSoroos** [comment]
This is basically an error that a web connection was interrupted, which isn't usually a big deal. 

Are most of the harvester runs running to completion, or are they mostly getting stopped?

**Comment by adinuca** [comment]
From the logs, it looks like the container stopes right after the error.

**Comment by EricSoroos** [comment]
Yes, but does it happen every day, or just occasionally?

**Comment by adinuca** [comment]
Every day, starting on the 19th of April.

**Comment by EricSoroos** [comment]
I've pushed an update to staging that should fix this.

**Comment by adinuca** [comment]
@EricSoroos here are the logs from the run from staging: https://papertrailapp.com/groups/3881793/events?q=harvester-staging-&focus=1070659830970212368

**Comment by adinuca** [comment]
@EricSoroos , although there were no more errors reported since the 12th of June, I think you should merge the fix.

Thank you!

**Comment by EricSoroos** [comment]
Ok, it's merged to master.
